language: python
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - sudo apt-get update
  - pip3 install coala-bears

services: docker
script: docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci